---
- name: "Find {{ title }}"
  find:
    path: "{{ path }}"
    recurse: "{{ recurse | default(True) }}"
    patterns: "{{ patterns | default(omit) }}"
    file_type: any
  register: found_

# Everything except directory structure will be purged
- name: "Remove unmanaged {{ title }}"
  file:
    path: "{{ item.path }}"
    state: absent
  when: >
    (not item.isdir and item.path|relpath(path) not in managed)
    or item.path|relpath(path) not in
      managed|map('truncate', item.path|relpath(path)|length, True, '')|unique(True)
  loop: "{{ found_.files | sort(True, attribute='path') }}"
  loop_control:
    label: "{{ item.path | relpath(path) }}"
  notify: "{{ notify | default([]) }}"
