---
driver:
  name: docker
lint:
  name: yamllint
  enabled: false
verifier:
  name: testinfra
  lint:
    name: flake8
platforms:
  - name: master-${MOLECULE_INSTANCE_SUFFIX:-instance}
    image: jakski/systemd:debian-10
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    tty: true
dependency:
  name: shell
  command: molecule/link-mitogen.sh
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      strategy_plugins: ${MOLECULE_SCENARIO_DIRECTORY}/plugins/strategy
      strategy: mitogen_linear
  playbooks:
    docker:
      create: ../docker-create.yml
    converge: playbook.yml
    side_effect: side-effect.yml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
